
# Language/versions
language: node_js
node_js:
  - "0.10"

# Build script
before_script:
  - npm install -g grunt-cli
script: 'grunt ci'

# Notifications
notifications:
  email:
    - notify+thingme@rowanmanning.co.uk
